DELETE http://localhost:3003/api/blogs/1 HTTP/1.1

###


DELETE http://localhost:3003/api/blogs/6733373b15e24d0a08e80f8f HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJiYiIsImlkIjoiNjcyY2RjNTUzYjFiMmFiMTcwMjYwYzI5IiwiaWF0IjoxNzMxNDEzMjc4LCJleHAiOjE3MzE0MTY4Nzh9.wodxEDFiqQQW9CPojabcw_2k1o5w3PBTKvXtOaGvtXo

###
DELETE http://localhost:3003/api/blogs/ HTTP/1.1